services:
  app:
    networks:
      - serve_os_shared

    build:
      context: .
      dockerfile: Dockerfile
      target: deps

    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    command: pnpm run dev

    restart: unless-stopped

networks:
  serve_os_shared:
    driver: bridge
    name: serve_os_shared

volumes:
  node_modules:
