/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffChangePasswordRouteImport } from './routes/staff-change-password'
import { Route as StaffAcceptInviteRouteImport } from './routes/staff-accept-invite'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SelectBusinessRouteImport } from './routes/select-business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerMenuRouteImport } from './routes/customer/menu'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AdminUserSettingsRouteImport } from './routes/_admin/user-settings'
import { Route as AdminTablesRouteImport } from './routes/_admin/tables'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminPaymentsRouteImport } from './routes/_admin/payments'
import { Route as AdminPaymentMethodsRouteImport } from './routes/_admin/payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminModifiersRouteImport } from './routes/_admin/modifiers'
import { Route as AdminMenuRouteImport } from './routes/_admin/menu'
import { Route as AdminKitchenRouteImport } from './routes/_admin/kitchen'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminBusinessesRouteImport } from './routes/_admin/businesses'
import { Route as AdminStaffIndexRouteImport } from './routes/_admin/staff/index'
import { Route as AdminStaffKitchenRouteImport } from './routes/_admin/staff/kitchen'

const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffChangePasswordRoute = StaffChangePasswordRouteImport.update({
  id: '/staff-change-password',
  path: '/staff-change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAcceptInviteRoute = StaffAcceptInviteRouteImport.update({
  id: '/staff-accept-invite',
  path: '/staff-accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectBusinessRoute = SelectBusinessRouteImport.update({
  id: '/select-business',
  path: '/select-business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/customer/menu',
  path: '/customer/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUserSettingsRoute = AdminUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModifiersRoute = AdminModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStaffRoute,
} as any)
const AdminStaffKitchenRoute = AdminStaffKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-business': typeof SelectBusinessRoute
  '/setup': typeof SetupRoute
  '/staff-accept-invite': typeof StaffAcceptInviteRoute
  '/staff-change-password': typeof StaffChangePasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/businesses': typeof AdminBusinessesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/kitchen': typeof AdminKitchenRoute
  '/menu': typeof AdminMenuRoute
  '/modifiers': typeof AdminModifiersRoute
  '/orders': typeof AdminOrdersRoute
  '/payment-methods': typeof AdminPaymentMethodsRoute
  '/payments': typeof AdminPaymentsRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRouteWithChildren
  '/tables': typeof AdminTablesRoute
  '/user-settings': typeof AdminUserSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/staff/kitchen': typeof AdminStaffKitchenRoute
  '/staff/': typeof AdminStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-business': typeof SelectBusinessRoute
  '/setup': typeof SetupRoute
  '/staff-accept-invite': typeof StaffAcceptInviteRoute
  '/staff-change-password': typeof StaffChangePasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/businesses': typeof AdminBusinessesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/kitchen': typeof AdminKitchenRoute
  '/menu': typeof AdminMenuRoute
  '/modifiers': typeof AdminModifiersRoute
  '/orders': typeof AdminOrdersRoute
  '/payment-methods': typeof AdminPaymentMethodsRoute
  '/payments': typeof AdminPaymentsRoute
  '/settings': typeof AdminSettingsRoute
  '/tables': typeof AdminTablesRoute
  '/user-settings': typeof AdminUserSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/staff/kitchen': typeof AdminStaffKitchenRoute
  '/staff': typeof AdminStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/select-business': typeof SelectBusinessRoute
  '/setup': typeof SetupRoute
  '/staff-accept-invite': typeof StaffAcceptInviteRoute
  '/staff-change-password': typeof StaffChangePasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/_admin/businesses': typeof AdminBusinessesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/kitchen': typeof AdminKitchenRoute
  '/_admin/menu': typeof AdminMenuRoute
  '/_admin/modifiers': typeof AdminModifiersRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/_admin/payments': typeof AdminPaymentsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/staff': typeof AdminStaffRouteWithChildren
  '/_admin/tables': typeof AdminTablesRoute
  '/_admin/user-settings': typeof AdminUserSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/_admin/staff/kitchen': typeof AdminStaffKitchenRoute
  '/_admin/staff/': typeof AdminStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/select-business'
    | '/setup'
    | '/staff-accept-invite'
    | '/staff-change-password'
    | '/staff-login'
    | '/businesses'
    | '/dashboard'
    | '/kitchen'
    | '/menu'
    | '/modifiers'
    | '/orders'
    | '/payment-methods'
    | '/payments'
    | '/settings'
    | '/staff'
    | '/tables'
    | '/user-settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/customer/menu'
    | '/staff/kitchen'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/select-business'
    | '/setup'
    | '/staff-accept-invite'
    | '/staff-change-password'
    | '/staff-login'
    | '/businesses'
    | '/dashboard'
    | '/kitchen'
    | '/menu'
    | '/modifiers'
    | '/orders'
    | '/payment-methods'
    | '/payments'
    | '/settings'
    | '/tables'
    | '/user-settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/customer/menu'
    | '/staff/kitchen'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/auth'
    | '/select-business'
    | '/setup'
    | '/staff-accept-invite'
    | '/staff-change-password'
    | '/staff-login'
    | '/_admin/businesses'
    | '/_admin/dashboard'
    | '/_admin/kitchen'
    | '/_admin/menu'
    | '/_admin/modifiers'
    | '/_admin/orders'
    | '/_admin/payment-methods'
    | '/_admin/payments'
    | '/_admin/settings'
    | '/_admin/staff'
    | '/_admin/tables'
    | '/_admin/user-settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/customer/menu'
    | '/_admin/staff/kitchen'
    | '/_admin/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  SelectBusinessRoute: typeof SelectBusinessRoute
  SetupRoute: typeof SetupRoute
  StaffAcceptInviteRoute: typeof StaffAcceptInviteRoute
  StaffChangePasswordRoute: typeof StaffChangePasswordRoute
  StaffLoginRoute: typeof StaffLoginRoute
  CustomerMenuRoute: typeof CustomerMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-change-password': {
      id: '/staff-change-password'
      path: '/staff-change-password'
      fullPath: '/staff-change-password'
      preLoaderRoute: typeof StaffChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-accept-invite': {
      id: '/staff-accept-invite'
      path: '/staff-accept-invite'
      fullPath: '/staff-accept-invite'
      preLoaderRoute: typeof StaffAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-business': {
      id: '/select-business'
      path: '/select-business'
      fullPath: '/select-business'
      preLoaderRoute: typeof SelectBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/menu': {
      id: '/customer/menu'
      path: '/customer/menu'
      fullPath: '/customer/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/user-settings': {
      id: '/_admin/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AdminUserSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tables': {
      id: '/_admin/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payment-methods': {
      id: '/_admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/modifiers': {
      id: '/_admin/modifiers'
      path: '/modifiers'
      fullPath: '/modifiers'
      preLoaderRoute: typeof AdminModifiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/menu': {
      id: '/_admin/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/kitchen': {
      id: '/_admin/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/businesses': {
      id: '/_admin/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/staff/': {
      id: '/_admin/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/_admin/staff/kitchen': {
      id: '/_admin/staff/kitchen'
      path: '/kitchen'
      fullPath: '/staff/kitchen'
      preLoaderRoute: typeof AdminStaffKitchenRouteImport
      parentRoute: typeof AdminStaffRoute
    }
  }
}

interface AdminStaffRouteChildren {
  AdminStaffKitchenRoute: typeof AdminStaffKitchenRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffKitchenRoute: AdminStaffKitchenRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface AdminRouteChildren {
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminModifiersRoute: typeof AdminModifiersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
  AdminTablesRoute: typeof AdminTablesRoute
  AdminUserSettingsRoute: typeof AdminUserSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminModifiersRoute: AdminModifiersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRouteWithChildren,
  AdminTablesRoute: AdminTablesRoute,
  AdminUserSettingsRoute: AdminUserSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  SelectBusinessRoute: SelectBusinessRoute,
  SetupRoute: SetupRoute,
  StaffAcceptInviteRoute: StaffAcceptInviteRoute,
  StaffChangePasswordRoute: StaffChangePasswordRoute,
  StaffLoginRoute: StaffLoginRoute,
  CustomerMenuRoute: CustomerMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
